### ISSUE TITLE
more information from powersensors

### ISSUE THREAD

**Issue by Mediacj** [wez3/domoboard#42]
Thanks again for this excellent dashboard 👍 

Is it possible to add the value of CounterToday and Usage? 

At the moment when you add a sensor for example a electric meter the total kWh is shown but I am also interested in the kWh usage of today(CounterToday) and the actual power in watt(Usage)

         "CounterToday" : "3.264 kWh",
         "Data" : "122332.324 kWh",
         "Usage" : "110.0 Watt",

**Comment by wez3** [comment]
I've modified Domoboard on the develop branch, see commit:
66f50dcc70b6de57b01d95bbf50471ea3abcb720

Can you test this on your Domoboard setup ?:) I guess it should work now. Here it does.

Just specify, e.g. "Usage" behind the top_tiles. (see example.conf)

**Comment by Mediacj** [comment]
I have tested it, it works perfect!

Thx!!

**Comment by wez3** [comment]
Great, thanks. Will be in master soon.
