### ISSUE TITLE
Default Raspbian Jessie full has flask-auth issues

### ISSUE THREAD

**Issue by wez3** [wez3/domoboard#43]
Default Raspbian Jessie full seems to have issues with the flask-auth module. Need to check this in a fresh Jessie full install.

**Comment by wez3** [comment]
I've been testing the installation on raspbian Jessie full + lite using virtualenv. The following seem to work on both OS's:

sudo apt-get install python-virtualenv
virtualenv /home/pi/domoboard/
cd /home/pi/domoboard/bin
source activate
cd ..
pip install -r requirements.txt
python server.py -c config.conf

**Comment by squandor** [comment]
i solved it on my machine by getting the package manually:
wget https://pypi.python.org/packages/b5/f5/0be3fa48160222a538d7db1715ea88ca8674aa2dbfcb2ba10b9cf47d16cd/Flask-Auth-0.85.tar.gz 
tar -zxvf Flask-Auth-0.85.tar.gz
cd Flask-Auth-0.85 
python setup.py install 

then it should work :)

**Comment by wez3** [comment]
Fixed in readme.
