### ISSUE TITLE
2 or more switch windows next to each other

### ISSUE THREAD

**Issue by Wizzard72** [wez3/domoboard#52]
Can we configure more than 2 switches windows next to each other?

**Comment by squandor** [comment]
not yet, at the moment we configured the windows to have 2 templates next to each other. 
We might need some more html css experience to fix this using the right method.

**Comment by wez3** [comment]
This has been implemented by using the following syntax:
  [[display_components]]
    components = switches[Switches 1], switches[Switches 2]
  [[switches]]
   [[[Switches 1]]]
   Auto opwarmen = 30, switch
   Auto ontdooien = 31, switch
   [[[Switches 2]]]
   Auto opwarmen = 30, switch
   Auto ontdooien = 31, switch

The names Switches 1 and Switches 2 can be anything you like to be displayed in the title bar.
