### ISSUE TITLE
Naming of News blocks

### ISSUE THREAD

**Issue by Sateetje** [wez3/domoboard#56]
It's is not possible to give the News blocks different names, like switches[Lamps], switches[Lamps2]

 news[NU.nl], news[112],

  [[news]]
    [[[NU.nl]]]
      rssfeed = http://www.nu.nl/rss/Algemeen
    [[[112]]]
      rssfeed = https://alarmeringen.nl/feeds/region/midden-en-west-brabant.rss

**Comment by squandor** [comment]
naming issue has been fixed in the last commit where the values like NU.nl and 112 are being used as Title if they are used.
