### ISSUE TITLE
Distance sensor doesn't work in Develop branch

### ISSUE THREAD

**Issue by Sateetje** [wez3/domoboard#57]
I've a distance sensor in Domoticz to measure the high of the salt level of my water softner.

This works in the Master branch (added as top_tile). But in the development branch no data is showed.

Btw: same with Wind sensor and TempHumBaro.

**Comment by wez3** [comment]
I've modified something today on this. Could you return me the information thats returned by the Domoticz API when requesting information about your distance sensor?
/json.htm?type=devices&rid=<IDX>

**Comment by Sateetje** [comment]
{
   "ActTime" : 1483860533,
   "ServerTime" : "2017-01-08 08:28:53",
   "Sunrise" : "08:47",
   "Sunset" : "16:50",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "28.0 cm",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "MySensors",
         "HardwareType" : "MySensors Gateway USB",
         "HardwareTypeVal" : 41,
         "HaveTimeout" : false,
         "ID" : "00000601",
         "LastUpdate" : "2017-01-08 08:24:58",
         "Name" : "Ontharder zout",
         "Notifications" : "true",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Distance",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "visibility",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "187"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by Sateetje** [comment]
Wind: 196.00;SSW;0;0;3.2;3.0" [Ricthing graden;Richting;Snelheid (bf);Windvlaag (bf);Temperatuur;Gevoelstemperatuur]

{
   "ActTime" : 1483860698,
   "ServerTime" : "2017-01-08 08:31:38",
   "Sunrise" : "08:47",
   "Sunset" : "16:50",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Chill" : 3.0,
         "CustomImage" : 0,
         "Data" : "196.00;SSW;0;0;3.2;3.0",
         "Description" : "",
         "Direction" : 196.0,
         "DirectionStr" : "SSW",
         "Favorite" : 1,
         "Gust" : "0",
         "HardwareID" : 13,
         "HardwareName" : "Weather Underground",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2017-01-08 08:23:50",
         "Name" : "Wind",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : [ 7 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Speed" : "0",
         "SubType" : "TFA",
         "Temp" : 3.20,
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : ,
         "idx" : "358"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by Sateetje** [comment]
TempHumBaro:

{
   "ActTime" : 1483860959,
   "ServerTime" : "2017-01-08 08:35:59",
   "Sunrise" : "08:47",
   "Sunset" : "16:50",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "Barometer" : 1031,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "3.3 C, 98 %, 1031 hPa",
         "Description" : "",
         "DewPoint" : "3.01",
         "Favorite" : 1,
         "Forecast" : 1,
         "ForecastStr" : "Sunny",
         "HardwareID" : 13,
         "HardwareName" : "Weather Underground",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "Humidity" : 98,
         "HumidityStatus" : "Wet",
         "ID" : "0001",
         "LastUpdate" : "2017-01-08 08:33:50",
         "Name" : "Buiten",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : [ 7 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "THB1 - BTHR918, BTHGN129",
         "Temp" : 3.30,
         "Timers" : "false",
         "Type" : "Temp + Humidity + Baro",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : ,
         "idx" : "357"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by Sateetje** [comment]
TempHum:

{
   "ActTime" : 1483861009,
   "ServerTime" : "2017-01-08 08:36:49",
   "Sunrise" : "08:47",
   "Sunset" : "16:50",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "4.2 C, 77 %",
         "Description" : "",
         "DewPoint" : "0.53",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 77,
         "HumidityStatus" : "Wet",
         "ID" : "510E",
         "LastUpdate" : "2017-01-08 08:36:06",
         "Name" : "Schuur",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "SubType" : "Cresta, TFA TS34C",
         "Temp" : 4.20,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "384"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by Sateetje** [comment]
Waterflow:
{
   "ActTime" : 1483866776,
   "ServerTime" : "2017-01-08 10:12:56",
   "Sunrise" : "08:47",
   "Sunset" : "16:50",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0.00 l/min",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "MySensors",
         "HardwareType" : "MySensors Gateway USB",
         "HardwareTypeVal" : 41,
         "HaveTimeout" : false,
         "ID" : "00004601",
         "Image" : "Moisture",
         "LastUpdate" : "2017-01-08 10:09:29",
         "Name" : "Water",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Waterflow",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "moisture",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "385"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by Sateetje** [comment]
This works: 
Buiten = 357, thermometer-half, **Barometer**
Zout = 187, spinner, **Data**

Maybe it is an idea to read the Data field when nothing specified?

**Comment by Sateetje** [comment]
This doesn't work (two times the same sensor):
    Wind (bf) = 358, cloud, Speed
    Windrichting = 358, cloud, DirectionStr

**Comment by Sateetje** [comment]
The On/Off switch doesn't work also:
    Patrick thuis = 380, info

{
   "ActTime" : 1483868207,
   "ServerTime" : "2017-01-08 10:36:47",
   "Sunrise" : "08:47",
   "Sunset" : "16:50",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 110,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Domoticz Slave",
         "HardwareType" : "Domoticz - Remote Server",
         "HardwareTypeVal" : 3,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014057",
         "Image" : "home",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-01-07 17:49:54",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Patrick is Thuis",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "380"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by Sateetje** [comment]
An overview of my test tiles. I think it would be nice to support different kind of sensors by default (with or without the right Units).

![tiles](https://cloud.githubusercontent.com/assets/16215404/21748807/ea6e0776-d58e-11e6-8fc2-6a5fef4c7888.png)

**Comment by wez3** [comment]
"Maybe it is an idea to read the Data field when nothing specified?"
This is already the case.

We've done yesterday some updates on develop. Can you check whether your devices (distance sensor) work with this update?

**Comment by Sateetje** [comment]
No data is shown. When I add ,Data, the right data is shown.

**Comment by Sateetje** [comment]
Distance sensor is working again.
