### ISSUE TITLE
Degrees Celcius isn't visible anymore

### ISSUE THREAD

**Issue by Sateetje** [wez3/domoboard#59]
The unit °C behind the temp sensors in the top_tiles isn't visible anymore.

**Comment by felix63** [comment]
This is the same issue as number #55 - close this one?

**Comment by Sateetje** [comment]
Not exactly the same.

#55 is about three values in one tile. That doesn't fit. It would be nice to order it in another way to see all the three values.

#59 is about the unit when temp sensor is used (temp only or temphumbaro)

**Comment by Sateetje** [comment]
Domoticz support multiple kind of temperature sensors, like Temp, TempHum and TempHumBaro.

It would be nice when all of the types are supported including the Units (C, % and hPa).
"Type" : "Temp": "Data" : "23.0 C",
"Type" : "Temp + Humidity": "Data" : "5.6 C, 79 %",
"Type" : "Temp + Humidity + Baro": "Data" : "5.4 C, 98 %, 1031 hPa",

I've tried this solution, but this doesn't work (two or more times the same sensor) and the Units are lost.
Buiten = 357, thermometer-half, Temp
Vochtigheid = 357, thermometer-half, Humidity
Luchtdruk = 357, thermometer-half, Barometer

**Comment by Sateetje** [comment]
The unit "C" is back behind the temperature. One part is solved :)
