### ISSUE TITLE
Multiple occurrences of top_tiles not working any more

### ISSUE THREAD

**Issue by felix63** [wez3/domoboard#60]
I had this

[buiten]
	[[display_components]]
		components = top_tiles[1], top_tiles[2], top_tiles[3], switches
	[[top_tiles]]
		[[[1]]]
			beweging = 32, tree
			tuindeur = 549, bell-o
			temp = 83, fire
			regen = 130, umbrella
		[[[2]]]
			beweging = 680, graduation-cap
			steeg = 35, male
			temp = 683, thermometer
			studio lux = 682, sun-o
		[[[3]]]
			beweging = 102, car
			garagedeur = 522, bell-o
			temp = 524, thermometer
			garage lux = 523, sun-o

Was working, showing different rows of tiles.. After the latest update in development it doesn't work any more. I really would like to have separate rows of tiles!

Cheers,
Lex

**Comment by wez3** [comment]
Reference:
66f50dcc70b6de57b01d95bbf50471ea3abcb720

**Comment by squandor** [comment]
just pushed an fix for this problem hopefully it will work on you're situation to.
