### ISSUE TITLE
On/Off state isn't displayed anymore

### ISSUE THREAD

**Issue by Sateetje** [wez3/domoboard#62]
The Tiles remains empty when using an On/Off switch.

Same issue as #57?

Develop branch

**Comment by wez3** [comment]
This is working for me. Please check your config, try first by only showing only the on/off state tile and add others later to debug the issue. Also make sure you have the newest version with git pull. Duplicate sensors might conflict each other like described in issue #61 and introduce other issues.

**Comment by Sateetje** [comment]
This is my config:
[general_settings]
  [[server]]
    url = 192.168.100.13:8080                   # IP-address of Domoticz backend
    flask_url = 192.168.100.228:80              # Please note: this is the internal IP-address including port of the Domoboard server
    user = username                     # Username for Domoticz (if required)
    password = password                 # Password for Domoticz (if required)
    secret_key = 6BaSYEI3ZcInlf31B4iU   # A random secret key used for Python authentication. Change to anything random.
  [[users]]
    username = password                 # Add users for Domoboard here. In this case login with username "username" and password "password"
  [[domoboard]]
    time = True
    date = True
    google_maps_api_key =

[navbar]
  [[menu]]
    Dashboard = dashboard, home
[dashboard]
  [[display_components]]
    components = top_tiles[Temp]
  [[top_tiles]]
    [[[Temp]]]
    Patrick thuis = 380, info

Using this git branch: 
git clone -b develop https://github.com/wez3/domoboard

API:
{
   "ActTime" : 1483897203,
   "ServerTime" : "2017-01-08 18:40:03",
   "Sunrise" : "08:47",
   "Sunset" : "16:50",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 110,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Domoticz Slave",
         "HardwareType" : "Domoticz - Remote Server",
         "HardwareTypeVal" : 3,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014057",
         "Image" : "home",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-01-07 17:49:54",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Patrick is Thuis",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "380"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

Still no data in the Tile:
![tileonoff](https://cloud.githubusercontent.com/assets/16215404/21752049/efc2758e-d5d1-11e6-96d0-2575dfded577.png)

**Comment by wez3** [comment]
Thanks for your detailed info. We've found the issue, however requires some big changes.

**Comment by wez3** [comment]
As temporary fix you can prevent using the subtitle block [[[Temp]]]. Without this block the top_tiles work.

**Comment by wez3** [comment]
Did some modification, can you test it? Also test #57 please :)

**Comment by Sateetje** [comment]
This issue is solved. Thank you!
