### ISSUE TITLE
Rain meter in top_tiles

### ISSUE THREAD

**Issue by felix63** [wez3/domoboard#63]
I have a rain meter. If I add a top tile for this device the value is reported as '0;0.7'. The first value is the current rainfall (in mm). The second value is the rainfall during the last 3 hours.

Representation of these values could be improved! It would be nice (als see #55) that if you have a device with several values you can choose which value to show and  to be able to use the same device multiple times with different values showing  (#61) - as @sateetje suggested.

Cheers,
Lex

**Comment by Sateetje** [comment]
Wind is also a nice one:
{
   "ActTime" : 1483897317,
   "ServerTime" : "2017-01-08 18:41:57",
   "Sunrise" : "08:47",
   "Sunset" : "16:50",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Chill" : 4.0,
         "CustomImage" : 0,
         "Data" : "213.00;SSW;0;0;4.5;4.0",
         "Description" : "",
         "Direction" : 213.0,
         "DirectionStr" : "SSW",
         "Favorite" : 1,
         "Gust" : "0",
         "HardwareID" : 13,
         "HardwareName" : "Weather Underground",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2017-01-08 18:34:18",
         "Name" : "Wind",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : [ 7 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Speed" : "0",
         "SubType" : "TFA",
         "Temp" : 4.50,
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cDovL3d3dy53dW5kZXJncm91bmQuY29tL2NnaS1iaW4vZmluZHdlYXRoZXIvZ2V0Rm9yZWNhc3Q/cXVlcnk9S2x1bmRlcnQ=",
         "idx" : "358"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by felix63** [comment]
Indeed!

**Comment by wez3** [comment]
I've updated domoboard for issue:
https://github.com/wez3/domoboard/issues/61

Also we've built the feature to select a specific field from the Json output that domoticz returns as you might already know:
https://github.com/wez3/domoboard/commit/66f50dcc70b6de57b01d95bbf50471ea3abcb720

Is there anything else, or can this issue be closed?

**Comment by felix63** [comment]
Works. Except that when displaying for data shows units because they are included in the value. When referencing specific values they are stored and displayed without any unit. My suggestion would be to add the unit as an extra parameter. E.g.

		vocht = 84, tint, HumidityStatus, %
		temp = 84, thermometer, Temp, c

**Comment by wez3** [comment]
I've just added this:
https://github.com/wez3/domoboard/commit/df97fe5a4552221ee5a85ae00a21e31dfcce16da

**Comment by felix63** [comment]
Is this ment to show units? Doesn’t work for me.

**Comment by wez3** [comment]
Yes, you can now add your own units. E.g.:
Totaal slaapkamer lamp = 52, plug, Usage, Watt

Make sure to clear your cache and to use the develop branch.

**Comment by felix63** [comment]
I am on develop branch. Did git pull. Cleared cache. Config is:
			temp = 83, thermometer, Temp, &deg;c
			regen = 130, umbrella, Rain, mm

But shows no units.

**Comment by squandor** [comment]
and if you only try the rain for now? maybe the server has difficulty's on the °c

**Comment by felix63** [comment]
I tried with only ‘c’. That didn’t work either.

**Comment by Sateetje** [comment]
I don't get Units also with this config:
    Buiten = 357, thermometer-half, Temp, C
    Vochtigheid = 357, thermometer-half, Humidity, %
    Luchtdruk = 357, thermometer-half, Barometer, hPa

**Comment by Sateetje** [comment]
Strange, this one works:
    Water vandaag = 356, shower, CounterToday, " l"

**Comment by squandor** [comment]
Hi all, i've tried al you're examples on an new test situation and everything works fine on mine 

Even did the config Buiten = idx, thermometer-half, Temp, C 
and my unit came up. so i don't understand why it doesn't work with you guys.

**Comment by wez3** [comment]
I also tried on a different setup (not my dev environment), and it worked after a pull request.. Even the...  °c

**Comment by felix63** [comment]
I checked if the changes you made are in top_tiles.html and domoboard.js and they are. Tried different browsers, cleared cache.

`# Add Navbar items here
[navbar]
	[[menu]]
		Dashboard = dashboard, dashboard
		Beneden = beneden, home
		Boven = boven, bed
		Buiten = buiten, bug
		Verwarming = verwarming, fire
		Mediacenter = mediacenter, film
		Weer = weer, snowflake-o
		Veiligheid = security, shield
		Verbruik = verbruik, line-chart
		Server = server, desktop
		Instellingen = instellingen, wrench

# Each navbar item needs a section. Components specify which components are displayed on the page. Other subsections contain names, Domoticz IDX's and options of the components displayed.
[dashboard]
	[[display_components]]
    		components = top_tiles, switches, news, dummy, icloud, wunderground[forecast], anwb, buienradar, map
  	[[top_tiles]]
    		Aanwezigheid = 86, male
		Woonkamer = 161, home, Temp
		Eetkamer = 505, cutlery, Temp
		Slaapkamer = 430, hotel, Temp
		Studio = 702, graduation-cap, Temp
		Tuin = 83, tree, Temp
	[[bar_charts]]
		Totaal slaapkamer lamp = 52
	[[switches]]
		TV kijken = 3, group
		Welterusten = 4, scene
		Alles uit = 5, scene
		Overdag = 12, scene
		Aanrecht = 280, switch
		tuinlicht = 21, switch
		fontein = 526, switch
		thermostaat = 436, setpoint
	[[news]]
			rssfeed = http://www.nu.nl/rss/Algemeen
	[[dummy]]
	[[icloud]]
	[[wunderground]]
		[[[forecast]]]
			Location = "Gouda, NL"
	[[anwb]]
	[[buienradar]]
	[[map]]
		Location = 685

[security]
	[[display_components]]
		components = top_tiles[1], top_tiles[2], camera[Steegzicht], camera[Tuinzicht], camera[Straatzicht]
	[[top_tiles]]
		[[[1]]]
			voordeur = 530, info
			raam voorkant = 149, info
			slaapkamerraam links = 33, info
			slaapkamerraam rechts = 152, info
			overloop = 73, eye
			garage = 522, car
		[[[2]]]
			eetkamer = 502, eye
			woonkamer = 159, eye
			tuin = 32, eye
			tuinhuis = 699, eye
			steeg = 35, eye
			garage = 102, eye
	[[camera]]
		[[[Steegzicht]]]
			Steegzicht = xxx
		[[[Tuinzicht]]]
			Tuinzicht = xxx
		[[[Straatzicht]]]
			Straatzicht = xxx


[beneden]
	[[display_components]]
		components = top_tiles[1], top_tiles[2],switches[Woonkamer],switches[Scenes],switches[Keuken],switches[Eetkamer], power_usage
	[[top_tiles]]
		[[[1]]]
			woonkamer = 159, home
			temperatuur = 161, fire 
			lux = 162, sun-o
			cv = 177, thermometer
			lucht = 493, cloud
		[[[2]]]
			eetkamer = 502, cutlery
			temperatuur = 505, fire 
			lux = 504, sun-o
			cv = 179, thermometer
			bel = 34, bell
  	[[switches]]
		[[[Woonkamer]]]
		    staande lamp  = 10, dimmer
			strip = 325, dimmer
			iris  = 11, rgb
			kubus = 79, dimmer	
			schotel = 335, dimmer
			spotjes = 506, dimmer
		[[[Scenes]]]
			TV kijken = 3, group
			Welterusten = 4, scene
			Alles uit = 5, scene
			Spelen = 9, group
			Bioscoop = 10, scene
			Overdag = 12, scene
		[[[Keuken]]]
			spotjes  = 280, switch
			boiler = 167, switch
			kerst = 633,switch
		[[[Eetkamer]]]
			lampje = 664, switch
	[[power_usage]]
		boiler = 170
		televisie = 137		

[boven]
	[[display_components]]
		components = top_tiles ,switches[Zolder],switches[Boven], domoticz_temp_charts
	[[top_tiles]]
		overloop = 73, eye
		temp = 430, thermometer, Temp
		cv = 262, fire
		gewicht = 100, balance-scale
		wasmachine = 139, cogs
		wasdroger = 142, cogs
	[[switches]]
		[[[Zolder]]]
			wasmachine = 694, switch
			wasdroger  = 695, switch
		[[[Boven]]]
			Bed Annet = 98, switch
			Bed Lex = 97, switch
	[[domoticz_temp_charts]]
		temp = 430, month, temperatuur

[buiten]
	[[display_components]]
		components = top_tiles[1], top_tiles[2], top_tiles[3], switches
	[[top_tiles]]
		[[[1]]]
			beweging = 32, tree
			tuindeur = 549, bell-o
			temp = 83, thermometer, Temp, " c"
			regen = 130, umbrella, Rain, " mm"
		[[[2]]]
			beweging = 699, graduation-cap
			steeg = 35, male
			temp = 702, thermometer
			studio lux = 701, sun-o
		[[[3]]]
			beweging = 102, car
			garagedeur = 522, bell-o
			temp = 524, thermometer
			garage lux = 523, sun-o
  	[[switches]]
		licht = 21, switch
		fontein = 526, switch
		garage = 525, switch

[verwarming]
  	[[display_components]]
    		components = top_tiles, switches[CV], switches[Radiatoren], domoticz_counter_charts, domoticz_smart_charts, domoticz_temp_charts, line_charts[cv], line_charts[flow], line_charts[studio]
	[[top_tiles]]
    		woonkamer = 161, thermometer
		eetkamer = 505, thermometer
		slaapkamer = 430, thermometer, Temp
		jochem = 437, thermometer
		studio = 702, thermometer
		CV = 554, fire
		
	[[switches]]
		[[[Radiatoren]]]
			woonkamer = 177, setpoint
			keuken = 271, setpoint
			hal = 268, setpoint
			eetkamer = 179, setpoint
			kleedkamer = 236, setpoint
			badkamer = 234, setpoint
		[[[CV]]]
			thermostaat = 436, setpoint
			tijdschakeling = 552, switch
			boiler = 435, switch
			radiatoren = 284, switch
	[[domoticz_counter_charts]]
		CV Pressure = 440, month, Pressure
	[[domoticz_smart_charts]]
		Gas = 555, month, gas
	[[domoticz_temp_charts]]
    		Temperatuur = 84, month, temp
	[[line_charts]]
		[[[cv]]]
			cv = 436, day, temp
		[[[flow]]]
			flow = 554, day, temp
		[[[studio]]]
			studio = 702, day, temp

[mediacenter]
  [[display_components]]
    components = top_tiles, tvgids, switches
  	[[top_tiles]]
		Dressoir = 431, fire, Temp, c
    		verbruik TV = 137, plug
		PS4 = 491, gamepad
	[[tvgids]]
	[[switches]]
		mute = 76, switch
		volume = 684, dimmer
		versterker = 391, switch
		subwoofer = 119, switch
		televisie = 132, switch
		ventilator = 38, switch

[weer]
  	[[display_components]]
    		components = top_tiles, wunderground[forecast], wunderground[condition], camera[Tuinzicht], buienradar, anwb, map
	[[top_tiles]]
		wind = 55, flag, DirectionStr
		kracht = 55, flag, Speed, "m/s"
		tuin = 83, tree, Temp
		garage = 524, car, Temp
		regen = 130, umbrella, Rain, " mm"
		vocht = 83, tint, HumidityStatus
	[[wunderground]]
		[[[forecast]]]
			Location = "Gouda, NL"
		[[[condition]]]
			Location = "Gouda, NL"
	[[camera]]
		[[[Tuinzicht]]]
			Tuinzicht = xxx
	[[buienradar]]
	[[anwb]]

[verbruik]
  	[[display_components]]
		components = top_tiles[1], top_tiles[2], domoticz_smart_charts[1], domoticz_smart_charts[2], domoticz_temp_charts
	[[top_tiles]]
		[[[1]]]
		Energie vandaag = 345, plug, CounterToday
		Energie gebruik= 345, flash, Usage
		Gas vandaag = 555, fire, CounterToday
		Gas gebruik = 555, fire, Counter
		[[[2]]]
		Wasmachine = 139, cogs
		Wasdroger = 142, cogs
		Televisie = 137, television
		Boiler = 170, fire
   	[[domoticz_smart_charts]]
		[[[1]]]
			Energie = 345, month, energy
		[[[2]]]
			Gas = 555, week, gas
	[[domoticz_temp_charts]]
		Temperatuur = 83, month, temp

[server]
	[[display_components]]
		components = top_tiles[1], top_tiles[2], top_tiles[3],serverlog
	[[top_tiles]]
		[[[1]]]
			Memory Pi = 1, percent
			Temp Pi = 4, fire
			CPU Pi = 5, percent
			HDD Pi = 3, hdd-o
		[[[2]]]
			Memory Syn = 114, percent
			Temp Syn = 107, fire
			CPU Syn = 113, percent
			HDD Syn = 112, hdd-o
		[[[3]]]
			Download = 630, download
			Upload = 631, upload
			Ping = 632, compress
			Vigilem = 492, video-camera

[instellingen]
	[[display_components]]
		components = settings
`

**Comment by squandor** [comment]
try to remove the quote around you're C 
my config looks like:  
 [[[Temp]]]
    Counter Woonkamer = 145, shower, Usage, %

**Comment by felix63** [comment]
Still doesn't work. Did you try on temperature devices?

**Comment by squandor** [comment]
ok so it seems to crash somewhere with the temp :) thanks now we know where to look :)

**Comment by squandor** [comment]
ok i've pushed an fix for this, could you check if it's working now?

**Comment by felix63** [comment]
<img width="397" alt="aanduiding" src="https://cloud.githubusercontent.com/assets/16501940/22028564/e8c71ebc-dcd7-11e6-99fd-5358a38197dd.png">

Yes it works, albeit that the ' c' I've added with the temp is smaller then the other 'C' that comes from data. But that's nitpicking.

**Comment by squandor** [comment]
indeed nitpicking haha 👍

**Comment by squandor** [comment]
is it okay to close this issue, we will work on the font later :)?

**Comment by felix63** [comment]
Sure. It's great that you solved it!
