### ISSUE TITLE
Setpoints

### ISSUE THREAD

**Issue by fergalom** [wez3/domoboard#65]
Can setpoints adjustment be via a dial or slider (with min / max defineable)?

Adjusting setpoints in Domoboard on a tablet with the current up/down arrows is very awkward

**Comment by squandor** [comment]
just added this feature to the develop branch. if you use the following config in you're .conf file it will create an slider: 
Thermostaat = 71, setpoint_slider, 18, 25 
18 is the min value and 25 the max value of the slider

**Comment by felix63** [comment]
It works. Whole points only. Is it difficult to make it move 0.5 point steps? I think I would like to have a little bit more control...

**Comment by squandor** [comment]
yeah me to, but i didn't found an solution to have 0.5 possibility's in the bootstrap slider. if you find one i will be happy to implement it :)!

**Comment by squandor** [comment]
just send an fix for the 0.5 numbers. If everything works you should use the slider and it will be using steps of 0.5 :) could you test if it works for you to? :)

**Comment by felix63** [comment]
Well done! That works just fine. 

Cheers,
Lex
