### ISSUE TITLE
Homescreen app requires re-login

### ISSUE THREAD

**Issue by wez3** [wez3/domoboard#67]
When adding domoboard to the homescreen on iPhone, it requires to logon every time when opening the app. We might find an alternative with an session time-out, so not every time authentication is required.

**Comment by dutchdevil83** [comment]
Also missing option to disable homescreen login

**Comment by squandor** [comment]
There has been an update in the develop branch where you can set the autologon function. if this is enabled you won't have to logon anymore in the homescreen
