### ISSUE TITLE
Top-tiles cropped

### ISSUE THREAD

**Issue by blackdog65** [wez3/domoboard#68]
When percentages are displayed in the top tiles, high numbers and specifically "100%" are cropped short on the right-hand side.
![top-tiles](https://cloud.githubusercontent.com/assets/18687297/21857531/b222269a-d81d-11e6-8dc8-8f1037176ffa.png)

**Comment by dutchdevil83** [comment]
This is happening with multiple items. Especially when displaying the pages on a tablet (in this case Ipad)

![domo1](https://cloud.githubusercontent.com/assets/25025717/21880965/f1966136-d8a1-11e6-80a9-f79fb1b73438.jpg)
![domo2](https://cloud.githubusercontent.com/assets/25025717/21880967/f1a8c0c4-d8a1-11e6-9215-f2ee0a2ed5ce.jpg)

**Comment by wez3** [comment]
I've pushed an update to the develop branch, which resizes the contents of the top tiles:
a7dbbe7375e73e18ccb2a7edab4d6dc81b592bd3

**Comment by wez3** [comment]
Please verify on your setups :)
