### ISSUE TITLE
Enhance installation of Domoboard and required modules

### ISSUE THREAD

**Issue by pvmil** [wez3/domoboard#74]
Is it possible to make installation of Domoboard (incl. plugins and required modules easier?)
similar to installing Domoticz for example? "sudo curl -L install.domoticz.com | bash"
as described on http://www.domoticz.com/wiki/Raspberry_Pi

**Comment by wez3** [comment]
You can also use the following commands to install domoboard:
git clone https://github.com/wez3/domoboard
cd domoboard
pip install -r requirements.txt

**Comment by wez3** [comment]
I've created your request. Changes can be seen at commit f50e9bd9f822e867c03ba46a94c5957f9f6bb9b8. 

Domoboard can now be installed with the following single command:
curl -L https://www.domoboard.nl/install | bash

**Comment by pvmil** [comment]
Nice thanks!
