### ISSUE TITLE
New version dumps on opening page

### ISSUE THREAD

**Issue by GuyThreepbush** [wez3/domoboard#80]
Had the earlier version running upgrading or even a clean install dumps on opening the service via a web page, Please note that I am running this on a synology. 

Would appreciate suggestions or a fix. Downgraded back to the previous versions for now.

`*Traceback (most recent call last):
 * File "/usr/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
 * File "/usr/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
 * File "/usr/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
*  File "/usr/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
 * File "/usr/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
*  File "/usr/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
 * File "/usr/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
*    rv = self.dispatch_request()
 * File "/usr/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
  *  return self.view_functions[rule.endpoint](**req.view_args)
 * File "/usr/lib/python2.7/site-packages/Flask_Auth-0.85-py2.7.egg/flaskext/auth/auth.py", line 186, in decorator
  *  return func(*args, **kwargs)
 * File "/volume1/homes/Guy/Domoboard/server.py", line 52, in generatePage
*    branch = webconfig.getCurrentBranch(),
 * File "/volume1/homes/Guy/Domoboard/modules/webconfig.py", line 26, in getCurrentBranch
    repo = git.Repo('.')
*  File "/usr/lib/python2.7/site-packages/GitPython-2.1.1-py2.7.egg/git/repo/base.py", line 156, in __init__
    raise InvalidGitRepositoryError(epath)
* InvalidGitRepositoryError: /volume1/homes/Guy/Domoboard`

**Comment by squandor** [comment]
make sure that you do an git clone on the synology nas. it uses the GitHub repo for the upgrade functionality

**Comment by GuyThreepbush** [comment]
Thank you for the quick response. Tried that earlier and could not find it. Now I quickly found that I needed to install the GIT server package on my synology. Working now.
