### ISSUE TITLE
Selector switch bug when "off-state" is hidden

### ISSUE THREAD

**Issue by dutchdevil83** [wez3/domoboard#84]
When the off status is hidden in domoticz the selector is not getting updated in the right way. The value is one step out of direction because the off state is not counted. Probably can be fixed when looking at the JSON response of the selector  `when LevelOffHidden = True then (selector_value - 1)` something like that..

**DOMOBOARD:**
![domoboard_selector](https://cloud.githubusercontent.com/assets/25025717/22195051/26bbef32-e146-11e6-8f5e-0e9240136b34.jpg)

**DOMOTICZ:**
![domoticz_selector](https://cloud.githubusercontent.com/assets/25025717/22195052/26bc5c38-e146-11e6-83c2-ad16475b57c8.jpg)

**Comment by squandor** [comment]
strange i will look into that tonight, should be a small fix on the develop branch.

**Comment by squandor** [comment]
had a little time :), just pusht the fix for this problem to the develop branch. does it work with you're situation now?

**Comment by dutchdevil83** [comment]
Yep fixed now. Thanx for the quick fix. Issue can be closed.
