### ISSUE TITLE
Wunderground Forecast not displayed

### ISSUE THREAD

**Issue by Sneeuwtijger** [wez3/domoboard#86]
in conf : 

[[wunderground]]
     [[[condition]]]
      location = Lelystad, NL
     [[[forecast]]]
      location = Lelystad, NL

Result in Domoboard : nothing

Syslog : 

`192.168.0.11 - - [24/Jan/2017 18:58:11] "POST /api?custom=wunderground&loc=Lelystad&country=GB&action=forecast HTTP/1.1" 500 -
Jan 24 18:58:11 raspberrypi server.py[29983]: Traceback (most recent call last):
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1994, in __call__
Jan 24 18:58:11 raspberrypi server.py[29983]: return self.wsgi_app(environ, start_response)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1985, in wsgi_app
Jan 24 18:58:11 raspberrypi server.py[29983]: response = self.handle_exception(e)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1540, in handle_exception
Jan 24 18:58:11 raspberrypi server.py[29983]: reraise(exc_type, exc_value, tb)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
Jan 24 18:58:11 raspberrypi server.py[29983]: response = self.full_dispatch_request()
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
Jan 24 18:58:11 raspberrypi server.py[29983]: rv = self.handle_user_exception(e)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
Jan 24 18:58:11 raspberrypi server.py[29983]: reraise(exc_type, exc_value, tb)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
Jan 24 18:58:11 raspberrypi server.py[29983]: rv = self.dispatch_request()
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
Jan 24 18:58:11 raspberrypi server.py[29983]: return self.view_functions[rule.endpoint](**req.view_args)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/usr/local/lib/python2.7/dist-packages/Flask_Auth-0.85-py2.7.egg/flaskext/auth/auth.py", line 186, in decorator
Jan 24 18:58:11 raspberrypi server.py[29983]: return func(*args, **kwargs)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/home/pi/domoboard/modules/api.py", line 43, in gateway
Jan 24 18:58:11 raspberrypi server.py[29983]: result = call(request.args)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/home/pi/domoboard/plugins/wunderground.py", line 66, in getData
Jan 24 18:58:11 raspberrypi server.py[29983]: data['forecastTxt'], data['forecastSimple'] = createForecast(requests.get(_url).text)
Jan 24 18:58:11 raspberrypi server.py[29983]: File "/home/pi/domoboard/plugins/wunderground.py", line 48, in createForecast
Jan 24 18:58:11 raspberrypi server.py[29983]: _simpleValues = _forecastSimple[next(index for (index, d) in enumerate(_forecastSimple) if d["date"]["weekday"] == _forecastTxt[idx]['weekday'])]
Jan 24 18:58:11 raspberrypi server.py[29983]: StopIteration`

**Comment by Sateetje** [comment]
NL doesn't work, Try EN for the Forecast

**Comment by squandor** [comment]
Indeed  nl doesn't work because the weekday can't. Be checked in nl. Sorry is an known bug.

**Comment by Sneeuwtijger** [comment]
Oké, I tried GB but I have to use EN, let's check out

**Comment by Sneeuwtijger** [comment]
It's alright now - I was mistaken - you have to set EN in the Wunderground settings, I thought I had to set that in the location, my mistake - works alright now ;)
