### ISSUE TITLE
Rainmeter from Underground Weather total rain not with 1 decimal

### ISSUE THREAD

**Issue by Sneeuwtijger** [wez3/domoboard#90]
Rainmeter from Underground Weather displays rain as such : 

![domoboard issue - rainmeter](https://cloud.githubusercontent.com/assets/24943584/22746857/8d45ab30-ee25-11e6-82bc-b4898cbb0a4e.png)

In Domoticz : 

![domoboard issue - rainmeter in domoticz](https://cloud.githubusercontent.com/assets/24943584/22746909/c1619276-ee25-11e6-82f6-451af8a6d29e.png)

In total value the decimal is missing.

**Comment by squandor** [comment]
hi @Sneeuwtijger it's true that the decimal is different in domoboard but thats because the data key from the json api returns an 0;0.0  what you could do is change you're config line of the rainmeter to this:
Rain meter = <idx>, rain, Rain, mm

**Comment by Sneeuwtijger** [comment]
Right, thx ;)
