### ISSUE TITLE
Refresh rss (news) feeds every 15 minutes or so

### ISSUE THREAD

**Issue by Sateetje** [wez3/domoboard#92]
Refresh rss (news) feeds every 15 minutes or so.

Now the rss feeds are static, you have to refresh manually.

**Comment by squandor** [comment]
hi Sateetje, just added an automatic update functionality to news. it will refresh now every 15 min.

**Comment by Sateetje** [comment]
Thanks! Just changed refresh to 15min :)

**Comment by squandor** [comment]
sorry my bad intervals are not my thing :)
