### ISSUE TITLE
Scrolling in left menu don't work well with Chrome browser for Android smartphone

### ISSUE THREAD

**Issue by miljume** [wez3/domoboard#94]
When viewing the Domoboard in Chrome with an Android (7.0) smartphone it is not possible to scroll down to the end of the left menu

Scrolling of the main page works fine

**Comment by Sateetje** [comment]
Same as #64?

**Comment by squandor** [comment]
jep indeed. we are still trying to solve this problem.

**Comment by squandor** [comment]
just pushed an possibly fix for this problem. it has been pushed to the develop branch. if you don't want to wait for the automatic update function in settings you can do an git pull

**Comment by miljume** [comment]
Thank's, sorry for not reading the existing issues before posting
