### ISSUE TITLE
Wunderground condition has rainfall in inches instead of mm

### ISSUE THREAD

**Issue by Sneeuwtijger** [wez3/domoboard#98]
[[wunderground]]
[[[condition]]]
location = City, NL

Rainfall: 0.01 mm

Value 0.01  is inches and not mm value 

Json part -
precip_today_string":"0.01 in (0 mm)",
		"precip_today_in":"0.01",
		"precip_today_metric":"0",

**Comment by squandor** [comment]
thank you i will change it in the plugin and send an update.

**Comment by wez3** [comment]
Fix was implemented in 0.0.8.
https://github.com/wez3/domoboard-plugins/commit/75108a2857515be7fb411d6ca563bef4635893cd
